apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscholar-gateway
  labels:
    app: oscholar-gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: oscholar-gateway
  template:
    metadata:
      labels:
        app: oscholar-gateway
    spec:
      imagePullSecrets:
        - name: oscholar-aliyun-acr-vpc-secret
      containers:
        - name: oscholar-gateway
          image: crpi-54xd1yj3irk9pgls.cn-shanghai.personal.cr.aliyuncs.com/oscholar/oscholar-gateway:placeholder
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http

          envFrom:
            - configMapRef:
                name: oscholar-gateway-config
            - secretRef:
                name: oscholar-gateway-secret

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
