apiVersion: v1
kind: Secret
metadata:
  name: oscholar-gateway-secret
type: Opaque
stringData:
  REDIS_HOST: "r-uf6cxsssx4idi2thix.redis.rds.aliyuncs.com"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "dev_oscholar"
  REDIS_PASSWORD: "Root123456!"
  REDIS_DB: "0"
