apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscholar-web
  labels:
    app: oscholar-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: oscholar-web
  template:
    metadata:
      labels:
        app: oscholar-web
    spec:
      imagePullSecrets:
        - name: oscholar-aliyun-acr-vpc-secret
      containers:
        - name: oscholar-web
          image: crpi-54xd1yj3irk9pgls.cn-shanghai.personal.cr.aliyuncs.com/oscholar/oscholar-web:placeholder
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 38088
              name: http

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
