apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscholar-web
  labels:
    app: oscholar-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: oscholar-web
  template:
    metadata:
      labels:
        app: oscholar-web
    spec:
      imagePullSecrets:
        - name: oscholar-aliyun-acr-vpc-secret
      containers:
        - name: oscholar-web
          image: crpi-54xd1yj3irk9pgls.cn-shanghai.personal.cr.aliyuncs.com/oscholar/oscholar-web:placeholder
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http

          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"

      volumes:
        - name: nginx-config
          configMap:
            name: oscholar-web-nginx-config
