apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: java-dev

namePrefix: dev-

images:
- name: crpi-54xd1yj3irk9pgls.cn-shanghai.personal.cr.aliyuncs.com/oscholar/oscholar-web:placeholder
  newName: crpi-54xd1yj3irk9pgls.cn-shanghai.personal.cr.aliyuncs.com/oscholar/oscholar-web
  newTag: "142"

resources:
- ../../base
- nginx-configmap.yaml
