apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscholar-paper
  labels:
    app: oscholar-paper
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: oscholar-paper
  template:
    metadata:
      labels:
        app: oscholar-paper
    spec:
      imagePullSecrets:
        - name: oscholar-aliyun-acr-vpc-secret
      containers:
        - name: oscholar-paper
          image: crpi-54xd1yj3irk9pgls.cn-shanghai.personal.cr.aliyuncs.com/oscholar/oscholar-paper:placeholder
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: oscholar-paper-config
            - secretRef:
                name: oscholar-paper-secret
          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
