apiVersion: v1
kind: Secret
metadata:
  name: oscholar-user-secret
type: Opaque
stringData:
  REDIS_HOST: "r-uf6cxsssx4idi2thix.redis.rds.aliyuncs.com"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "dev_oscholar"
  REDIS_PASSWORD: "Root123456!"
  REDIS_DB: "0"
  DB_HOST: "rm-uf6i96l1sh863ky29.mysql.rds.aliyuncs.com"
  DB_PORT: "63306"
  DB_NAME: "dev_oscholar_user"
  DB_USERNAME: "oscholar_dev"
  DB_PASSWORD: "Root123456!"
